export const person = {
  name: "Salma Shaik",
  title: "Microsoft Power Apps & Dynamics 365 CE Developer",
  experience: "4+",
  company: "Starlite Infotech",
  location: "Guntur, Andhra Pradesh, India",
  phone: "+91 8639420642",
  email: "sksalma9177@gmail.com",
  summary:
    "Microsoft Power Apps and Dynamics 365 CE Developer with 4+ years of experience at Starlite Infotech building and supporting enterprise CRM solutions on Dynamics 365 CE, Dataverse, and Power Automate. Hands-on with Model-Driven Apps, synchronous and asynchronous C#.NET plugins, custom workflow activities, JavaScript form scripting, Business Process Flows, business rules, and Ribbon Workbench customization. Experienced with FetchXML, WebAPI, and REST integrations, SSIS and CRM SDK data migration, SSRS reporting, security roles and record-level access, and solution management across development, UAT, and production.",
};

export const skills = [
  {
    category: "Dynamics 365 / CRM",
    icon: "dynamics",
    color: "#0078d4",
    items: [
      "Dynamics 365 CE",
      "Microsoft Dynamics CRM 2016",
      "Dynamics 365 Sales",
      "Sales Hub",
      "Model-Driven Apps",
      "Business Process Flows",
      "Business Rules",
      "Plugins",
      "Custom Workflow Activities",
      "Security Roles",
      "Record-Level Security",
      "Solution Management",
    ],
  },
  {
    category: "Power Platform",
    icon: "power",
    color: "#742774",
    items: [
      "Power Apps",
      "Model-Driven Apps",
      "Canvas Apps",
      "Power Automate",
      "Microsoft Dataverse",
    ],
  },
  {
    category: "Programming",
    icon: "code",
    color: "#7c3aed",
    items: ["C#.NET", "JavaScript", "HTML", "CSS"],
  },
  {
    category: "Integration",
    icon: "integration",
    color: "#0ea5e9",
    items: ["WebAPI", "OData", "FetchXML", "REST APIs", "CRM SDK"],
  },
  {
    category: "Data & Reporting",
    icon: "data",
    color: "#10b981",
    items: [
      "SQL Server",
      "SSIS",
      "SSRS",
      "KingswaySoft",
      "Data Migration",
      "Data Validation",
    ],
  },
  {
    category: "Tools",
    icon: "tools",
    color: "#f59e0b",
    items: ["Ribbon Workbench", "XrmToolBox", "REST Builder", "Visual Studio"],
  },
];

export const experience = [
  {
    company: "Starlite Infotech",
    role: "Power Apps Developer",
    period: "August 2022 – Present",
    domain: "Energy Management · Manufacturing Sales · Social Services",
    responsibilities: [
      "Develop and support Dynamics 365 CE and Power Platform solutions for enterprise clients in energy management, manufacturing sales, and social services.",
      "Build synchronous and asynchronous C#.NET plugins and custom workflow activities for validation, calculations, escalations, and process automation.",
      "Implement JavaScript form scripts, business rules, and Ribbon Workbench command customizations for real-time validation and guided user actions.",
      "Configure Dataverse entities and relationships, Business Process Flows, forms, views, charts, and dashboards in Model-Driven Apps.",
      "Build Power Automate flows for notifications, lead assignment, escalations, approvals, and data archiving.",
      "Develop FetchXML queries, WebAPI integrations, and SSRS reports; support SSIS and CRM SDK data migration with post-migration validation.",
      "Configure security roles and record-level access; manage solutions across development, UAT, and production; handle functional, regression, and UAT testing and production support.",
    ],
  },
];

export const projects = [
  {
    id: "energy-financials",
    title: "Energy Financials",
    client: "Microsoft Cloud Operations",
    domain: "Energy Management & Cloud Operations",
    role: "D365 CE Developer / Power Apps Developer",
    tech: [
      "Dynamics 365 CE",
      "Dataverse",
      "Power Apps",
      "Power Automate",
      "C#.NET",
      "JavaScript",
      "WebAPI",
      "FetchXML",
      "Ribbon Workbench",
    ],
    description:
      "Centralized Dynamics 365 CE solution that consolidates energy usage and spending data from multiple utility providers, replacing fragmented Excel-based tracking.",
    highlights: [
      "Developed synchronous and asynchronous C#.NET plugins for energy data validation, consumption tracking, and utility provider reconciliation.",
      "Created Dataverse entities for Energy Providers, Utility Accounts, Consumption Records, and Billing Data with structured utility data relationships.",
      "Wrote JavaScript form scripts for real-time validation, dynamic consumption calculations, and billing calculation checks; configured business rules for data quality.",
      "Built an interactive energy consumption dashboard using HTML, CSS, and JavaScript.",
      "Customized command bar actions with Ribbon Workbench, including bulk data import and utility provider registration.",
      "Wrote FetchXML queries for consumption aggregations and billing summaries, and WebAPI calls for data retrieval and integration.",
      "Built Power Automate flows for automated notifications and data archiving.",
      "Configured security roles and record-level access; managed solution deployment across dev, UAT, and production.",
    ],
    flow: [
      "Utility Providers",
      "Dataverse",
      "Dynamics 365 CE",
      "Business Logic",
      "Power Automate",
      "Dashboards / Reporting",
    ],
    metric: { value: "~85%", label: "Reduction in manual data-entry activities" },
    color: "#0078d4",
  },
  {
    id: "coats-group",
    title: "Coats Group",
    subtitle: "Dynamics 365 CE Sales Implementation",
    client: "Coats Group PLC",
    domain: "Manufacturing & Global Sales Operations",
    role: "CRM Developer / Power Apps Developer",
    tech: [
      "Dynamics 365 CE",
      "Power Apps",
      "Dataverse",
      "SQL Server 2016",
      "SSIS",
      "CRM SDK",
      "Power Automate",
      "FetchXML",
      "SSRS",
      "JavaScript",
    ],
    description:
      "Dynamics 365 CE Sales implementation for a global manufacturer covering account management, lead-to-opportunity processes, quotations, orders, and regional sales operations.",
    highlights: [
      "Worked with regional sales requirements to build out Account, Contact, Lead, Opportunity, Quote, and Order data models.",
      "Configured Sales Hub components and customized forms, views, charts, and dashboards.",
      "Implemented Business Process Flows for lead qualification and opportunity management with conditional stage transitions.",
      "Configured multi-level security roles, record-level sharing rules, entity relationships, and cascading behaviors.",
      "Developed SSIS packages and used the CRM SDK to migrate customer, product, and historical sales data; validated migrated records and resolved data-quality issues.",
      "Built Power Automate flows for lead assignment, opportunity escalation, and quote approval notifications.",
      "Developed FetchXML queries for sales metrics and SSRS reports for pipeline and forecasting.",
      "Managed solutions across development, sandbox, and production; performed functional, regression, and UAT testing and supported production cutover.",
    ],
    flow: ["Lead", "Qualification", "Opportunity", "Quote", "Order"],
    metrics: [
      { value: "500+", label: "Regional sales users" },
      { value: "8", label: "Geographical regions" },
    ],
    color: "#742774",
  },
  {
    id: "avutox",
    title: "Avutox",
    subtitle: "Child Safety & Family Services CRM Platform",
    client: "Avutox",
    domain: "Social Services & Child Welfare",
    role: "CRM Developer / Power Apps Developer",
    tech: [
      "Microsoft Dynamics CRM 2016",
      "Dynamics 365 CE",
      "Dataverse",
      "Power Apps",
      "Power Automate",
      "JavaScript",
      "C#.NET",
      "Business Process Flows",
      "FetchXML",
    ],
    description:
      "CRM platform supporting case intake, family assessment, service planning, service delivery tracking, and outcome management for a child safety and family services organization.",
    highlights: [
      "Built custom entities for Family Records, Child Cases, Case Workers, Service Plans, and Service Delivery with configured relationships.",
      "Wrote JavaScript validation for case intake and assessment forms; configured business rules for mandatory fields and assessment checks.",
      "Developed synchronous and asynchronous C#.NET plugins and custom workflow activities, including automatic case escalation logic.",
      "Customized Ribbon Workbench command bars for case escalation and service-plan actions.",
      "Configured a Business Process Flow covering Intake, Assessment, Service Planning, Service Delivery, and Outcome Measurement.",
      "Configured security roles and record-level access separating case-worker and supervisor permissions.",
      "Developed FetchXML queries and reports; managed solution deployment, system testing, and resolution of workflow and data-consistency issues.",
    ],
    flow: [
      "Intake",
      "Assessment",
      "Service Planning",
      "Service Delivery",
      "Outcome Measurement",
    ],
    metric: { value: "5,000+", label: "Active cases supported" },
    color: "#10b981",
  },
];

export const impactStats = [
  {
    value: 85,
    suffix: "%",
    prefix: "~",
    label: "Reduction in manual data-entry activities",
    project: "Energy Financials",
    color: "#0078d4",
  },
  {
    value: 500,
    suffix: "+",
    label: "Regional sales users",
    project: "Coats Group",
    color: "#742774",
  },
  {
    value: 8,
    suffix: "",
    label: "Geographical regions served",
    project: "Coats Group",
    color: "#7c3aed",
  },
  {
    value: 5000,
    suffix: "+",
    label: "Active cases supported",
    project: "Avutox",
    color: "#10b981",
  },
];

export const education = [
  {
    degree: "B.Sc. (MPCS)",
    institution: "ASN Degree College, Tenali",
    university: "Acharya Nagarjuna University",
    year: "2022",
    score: "80%",
  },
  {
    degree: "Intermediate",
    institution: "NRI Junior College, Tenali",
    university: "",
    year: "2019",
    score: "87%",
  },
  {
    degree: "SSC",
    institution: "Z.P.G. High School, Duggirala",
    university: "",
    year: "2017",
    score: "86%",
  },
];
